"""Initial schema — ``node`` table.

Revision ID: 0001_initial_schema
Revises:
Create Date: 2026-04-20

This migration is hand-written rather than autogenerated: it lets the
repo ship a working DB bootstrap *before* anyone has run
``alembic revision --autogenerate`` locally. The column set matches
``tairos_api.models.node.Node`` one-for-one; future migrations should
be autogenerated as usual.
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision:       str                         = "0001_initial_schema"
down_revision:  str | Sequence[str] | None  = None
branch_labels:  str | Sequence[str] | None  = None
depends_on:     str | Sequence[str] | None  = None


def upgrade() -> None:
    op.create_table(
        "node",
        sa.Column("id",         sa.String(length=64),  primary_key=True),
        sa.Column("operator",   sa.String(length=4),   nullable=False),
        sa.Column("name",       sa.String(length=120), nullable=False),
        sa.Column("lat",        sa.Float(),            nullable=False),
        sa.Column("lng",        sa.Float(),            nullable=False),
        sa.Column("extra",      sa.JSON(),             nullable=False),
        sa.Column("created_at", sa.DateTime(),         nullable=False),
        sa.Column("updated_at", sa.DateTime(),         nullable=False),
    )
    # Operator-scoped lookups are the hot path ("give me TR nodes").
    # An index here makes that O(log n) from day one.
    op.create_index("ix_node_operator", "node", ["operator"])


def downgrade() -> None:
    op.drop_index("ix_node_operator", table_name="node")
    op.drop_table("node")
